spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect=org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_REST_API_KEY}
            client-secret: ${OAUTH_KAKAO_SECRET}
            redirect-uri: ${OAUTH_KAKAO_DEV_REDIRECT_URI}
            scope:
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id