spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_MYSQL_DATABASE_HOST}:${DEV_MYSQL_DATABASE_PORT}/${DEV_MYSQL_DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DEV_MYSQL_DATABASE_USERNAME}
    password: ${DEV_MYSQL_DATABASE_PASSWORD}

  redis:
    session:
      host: ${DEV_SESSION_HOST}
      port: ${DEV_SESSION_PORT}
      password: ${DEV_SESSION_PASSWORD}
      ssl:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_KAKAO_REST_API_KEY}
            client-secret: ${OAUTH_KAKAO_SECRET}
            redirect-uri: "http://localhost:3000/auth/callback/kakao"
            scope:
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expired-time-ms: 604800000 #1일
  refresh-expired-time-ms: 2592000000 #30일
